[package]
name = "tect_camera"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17"
tect_state = { path = "../tect_state", version = "0.1.0", default-features = false }

[lints]
workspace = true
